CREATE TABLE IF NOT EXISTS USER (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(50) NOT NULL,
    prenom VARCHAR(50) NOT NULL,
    sexe VARCHAR(15) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    hash VARCHAR(100) NOT NULL,
    active int(1) NOT NULL DEFAULT '0',
    UNIQUE KEY unique_email (email)
);



CREATE TABLE IF NOT EXISTS EVENTS (
    user_id INT NOT NULL,
    unique_id INT AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    eventType VARCHAR(30),
    date VARCHAR(100),
    startTime VARCHAR(100),
    endTime VARCHAR(100),
    allDay BOOLEAN

) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS ENTRAINEMENT (
    user_id INT NOT NULL,
    unique_id INT NOT NULL,
    modalite VARCHAR(100),
    autre VARCHAR(100),
    duree TIME,
    rating INT,
    type VARCHAR(100),
    denivele FLOAT,
    distance FLOAT,
    autre_session VARCHAR(10)

) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS HEBDOMADAIRE (
    user_id INT NOT NULL,
    unique_id INT NOT NULL,
    poids FLOAT,
    niveau_forme INT,
    blesse VARCHAR(3),
    fatigue_generale INT,
    douleurs_jambes INT,
    stress INT,
    parcours_habituel VARCHAR(3),
    temps TIME,
    fc INT
    

) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS TEMPS_REACTION (
    user_id INT NOT NULL,
    unique_id INT NOT NULL,
    TR1 INT,
    TR2 INT,
    TR3 INT,
    TR4 INT,
    TR5 INT,
    TR6 INT,
    TR7 INT,
    TR8 INT,
    TR9 INT,
    TR10 INT,
    TR11 INT,
    TR12 INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS SOMMEIL (
    user_id INT NOT NULL,
    unique_id INT NOT NULL,
    Q1 TIME,
    Q2 TIME,
    Q3 VARCHAR(300),
    Q4 VARCHAR(300),
    Q5 VARCHAR(300),
    Q6 VARCHAR(300),
    Q7 VARCHAR(300),
    Q8 VARCHAR(300),
    Q9 VARCHAR(500)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS BLESSURE (
    user_id INT NOT NULL,
    unique_id INT NOT NULL,
    Q1 VARCHAR(3),
    Q2 VARCHAR(10),
    Q3 VARCHAR(300),
    Q4 VARCHAR(300),
    Q5 VARCHAR(300),
    Q6 VARCHAR(300),
    Q7 VARCHAR(300),
    Q8 VARCHAR(300),
    Q9 VARCHAR(300),
    Q10 VARCHAR(300),
    Q11 VARCHAR(300),
    Q12 VARCHAR(300)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS SURENTRAINEMENT (
    user_id INT NOT NULL,
    unique_id INT NOT NULL,
    Q1 INT,
    Q2 INT,
    Q3 INT,
    Q4 INT,
    Q5 INT,
    Q6 INT,
    Q7 VARCHAR(3) NOT NULL,
    Q8 VARCHAR(3) NOT NULL,
    Q9 VARCHAR(3) NOT NULL,
    Q10 VARCHAR(3) NOT NULL,
    Q11 VARCHAR(3) NOT NULL,
    Q12 VARCHAR(3) NOT NULL,
    Q13 VARCHAR(3) NOT NULL,
    Q14 VARCHAR(3) NOT NULL,
    Q15 VARCHAR(3) NOT NULL,
    Q16 VARCHAR(3) NOT NULL,
    Q17 VARCHAR(3) NOT NULL,
    Q18 VARCHAR(3) NOT NULL,
    Q19 VARCHAR(3) NOT NULL,
    Q20 VARCHAR(3) NOT NULL,
    Q21 VARCHAR(3) NOT NULL,
    Q22 VARCHAR(3) NOT NULL,
    Q23 VARCHAR(3) NOT NULL,
    Q24 VARCHAR(3) NOT NULL,
    Q25 VARCHAR(3) NOT NULL,
    Q26 VARCHAR(3) NOT NULL,
    Q27 VARCHAR(3) NOT NULL,
    Q28 VARCHAR(3) NOT NULL,
    Q29 VARCHAR(3) NOT NULL,
    Q30 VARCHAR(3) NOT NULL,
    Q31 VARCHAR(3) NOT NULL,
    Q32 VARCHAR(3) NOT NULL,
    Q33 VARCHAR(3) NOT NULL,
    Q34 VARCHAR(3) NOT NULL,
    Q35 VARCHAR(3) NOT NULL,
    Q36 VARCHAR(3) NOT NULL,
    Q37 VARCHAR(3) NOT NULL,
    Q38 VARCHAR(3) NOT NULL,
    Q39 VARCHAR(3) NOT NULL,
    Q40 VARCHAR(3) NOT NULL,
    Q41 VARCHAR(3) NOT NULL,
    Q42 VARCHAR(3) NOT NULL,
    Q43 VARCHAR(3) NOT NULL,
    Q44 VARCHAR(3) NOT NULL,
    Q45 VARCHAR(3) NOT NULL,
    Q46 VARCHAR(3) NOT NULL,
    Q47 VARCHAR(3) NOT NULL,
    Q48 VARCHAR(3) NOT NULL,
    Q49 VARCHAR(3) NOT NULL,
    Q50 VARCHAR(3) NOT NULL,
    Q51 VARCHAR(3) NOT NULL,
    Q52 VARCHAR(3) NOT NULL,
    Q53 VARCHAR(3) NOT NULL,
    Q54 VARCHAR(3) NOT NULL,
    Q55 VARCHAR(3) NOT NULL,
    Q56 VARCHAR(3) NOT NULL,
    Q57 VARCHAR(3) NOT NULL,
    Q58 VARCHAR(3) NOT NULL,
    Q59 VARCHAR(3) NOT NULL,
    Q60 VARCHAR(3) NOT NULL
    

) ENGINE=InnoDB DEFAULT CHARSET=utf8;
